package com.w3plus.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PickingPointAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPickingPointAllPropertiesEquals(PickingPoint expected, PickingPoint actual) {
        assertPickingPointAutoGeneratedPropertiesEquals(expected, actual);
        assertPickingPointAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPickingPointAllUpdatablePropertiesEquals(PickingPoint expected, PickingPoint actual) {
        assertPickingPointUpdatableFieldsEquals(expected, actual);
        assertPickingPointUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPickingPointAutoGeneratedPropertiesEquals(PickingPoint expected, PickingPoint actual) {
        assertThat(expected)
            .as("Verify PickingPoint auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPickingPointUpdatableFieldsEquals(PickingPoint expected, PickingPoint actual) {
        assertThat(expected)
            .as("Verify PickingPoint relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getAdresse()).as("check adresse").isEqualTo(actual.getAdresse()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPickingPointUpdatableRelationshipsEquals(PickingPoint expected, PickingPoint actual) {}
}
